resolver: lts-6.1

nix:
  enable: true
  packages:
    - zlib
    - haskellPackages.hscolour

packages:
- '.'

extra-deps:
- attoparsec-binary-0.2
- smallcheck-series-0.5.1

flags: {}

extra-package-dbs: []
